### ISSUE TITLE
gazebo 화면 런치하는 중 오류

### ISSUE THREAD

**Issue by ghost** [kimsooyoung/AIDL_ip010_lecture#4]
실행하니아래와 같은 에러가 발생하면서 켜지지 않습니다..
아까와 같은 에러인거같은데 source /usr/share/gazebo/setup.sh 해도 ㅠㅠ 똑같은에러가 뜹니다 ㅠㅠ

### (ROS 2 foxy) aidl@aidl-NUC11BTMi7:~/aidl_ws$ ros2 launch ip010_gazebo empty_world.launch.py
[INFO] [launch]: All log files can be found below /home/aidl/.ros/log/2022-07-29-16-12-48-442319-aidl-NUC11BTMi7-7812
[INFO] [launch]: Default logging verbosity is set to INFO
Task exception was never retrieved
future: <Task finished name='Task-2' coro=<LaunchService._process_one_event() done, defined at /opt/ros/foxy/lib/python3.8/site-packages/launch/launch_service.py:226> exception=PackageNotFoundError("package 'rqt_robot_steering' not found, searching: ['/home/aidl/aidl_ws/install/nav2_rosdevday_2021', '/home/aidl/aidl_ws/install/ip010_slam', '/home/aidl/aidl_ws/install/ip010_nav', '/home/aidl/aidl_ws/install/ip010_gazebo', '/home/aidl/aidl_ws/install/ip010_description', '/home/aidl/aidl_ws/install/ip010_amcl', '/home/aidl/aidl_ws/install/gazebo_utils', '/home/aidl/aidl_ws/install/aws_robomaker_small_warehouse_world', '/opt/ros/foxy']")>
Traceback (most recent call last):
  File "/opt/ros/foxy/lib/python3.8/site-packages/ament_index_python/packages.py", line 50, in get_package_prefix
    content, package_prefix = get_resource('packages', package_name)
  File "/opt/ros/foxy/lib/python3.8/site-packages/ament_index_python/resources.py", line 48, in get_resource
    raise LookupError(
LookupError: Could not find the resource 'rqt_robot_steering' of type 'packages'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_service.py", line 228, in _process_one_event
    await self.__process_event(next_event)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_service.py", line 248, in __process_event
    visit_all_entities_and_collect_futures(entity, self.__context))
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 45, in visit_all_entities_and_collect_futures
    futures_to_return += visit_all_entities_and_collect_futures(sub_entity, context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 45, in visit_all_entities_and_collect_futures
    futures_to_return += visit_all_entities_and_collect_futures(sub_entity, context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 45, in visit_all_entities_and_collect_futures
    futures_to_return += visit_all_entities_and_collect_futures(sub_entity, context)
  [Previous line repeated 1 more time]
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 38, in visit_all_entities_and_collect_futures
    sub_entities = entity.visit(context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/action.py", line 108, in visit
    return self.execute(context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch_ros/actions/node.py", line 453, in execute
    ret = super().execute(context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/actions/execute_process.py", line 823, in execute
    self.__expand_substitutions(context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/actions/execute_process.py", line 668, in __expand_substitutions
    cmd = [perform_substitutions(context, x) for x in self.__cmd]
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/actions/execute_process.py", line 668, in <listcomp>
    cmd = [perform_substitutions(context, x) for x in self.__cmd]
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/perform_substitutions_impl.py", line 26, in perform_substitutions
    return ''.join([context.perform_substitution(sub) for sub in subs])
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/perform_substitutions_impl.py", line 26, in <listcomp>
    return ''.join([context.perform_substitution(sub) for sub in subs])
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_context.py", line 197, in perform_substitution
    return substitution.perform(self)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch_ros/substitutions/executable_in_package.py", line 76, in perform
    package_prefix = super().perform(context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch_ros/substitutions/find_package.py", line 79, in perform
    result = self.find(package)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch_ros/substitutions/find_package.py", line 96, in find
    return get_package_prefix(package_name)
  File "/opt/ros/foxy/lib/python3.8/site-packages/ament_index_python/packages.py", line 52, in get_package_prefix
    raise PackageNotFoundError(
ament_index_python.packages.PackageNotFoundError: "package 'rqt_robot_steering' not found, searching: ['/home/aidl/aidl_ws/install/nav2_rosdevday_2021', '/home/aidl/aidl_ws/install/ip010_slam', '/home/aidl/aidl_ws/install/ip010_nav', '/home/aidl/aidl_ws/install/ip010_gazebo', '/home/aidl/aidl_ws/install/ip010_description', '/home/aidl/aidl_ws/install/ip010_amcl', '/home/aidl/aidl_ws/install/gazebo_utils', '/home/aidl/aidl_ws/install/aws_robomaker_small_warehouse_world', '/opt/ros/foxy']"
Task exception was never retrieved
future: <Task finished name='Task-25' coro=<LaunchService._process_one_event() done, defined at /opt/ros/foxy/lib/python3.8/site-packages/launch/launch_service.py:226> exception=RuntimeError('Signal event received before subprocess transport available.')>
Traceback (most recent call last):
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_service.py", line 228, in _process_one_event
    await self.__process_event(next_event)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_service.py", line 248, in __process_event
    visit_all_entities_and_collect_futures(entity, self.__context))
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 38, in visit_all_entities_and_collect_futures
    sub_entities = entity.visit(context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/action.py", line 108, in visit
    return self.execute(context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/actions/opaque_function.py", line 75, in execute
    return self.__function(context, *self.__args, **self.__kwargs)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/actions/execute_process.py", line 443, in __on_signal_process_event
    raise RuntimeError('Signal event received before subprocess transport available.')
RuntimeError: Signal event received before subprocess transport available.
[INFO] [gzserver-1]: process started with pid [7814]
[INFO] [gzclient   -2]: process started with pid [7816]
[INFO] [robot_state_publisher-3]: process started with pid [7820]
[INFO] [joint_state_publisher-4]: process started with pid [7822]
[INFO] [spawn_entity.py-5]: process started with pid [7824]
[INFO] [joint_state_publisher-4]: sending signal 'SIGINT' to process[joint_state_publisher-4]
[INFO] [robot_state_publisher-3]: sending signal 'SIGINT' to process[robot_state_publisher-3]
[INFO] [gzclient   -2]: sending signal 'SIGINT' to process[gzclient   -2]
[ERROR] [joint_state_publisher-4]: process has died [pid 7822, exit code -2, cmd '/opt/ros/foxy/lib/joint_state_publisher/joint_state_publisher --ros-args -r __node:=joint_state_publisher'].
[INFO] [gzserver-1]: sending signal 'SIGINT' to process[gzserver-1]
[robot_state_publisher-3] [INFO] [1659078768.790443867] [rclcpp]: signal_handler(signal_value=2)
[robot_state_publisher-3] terminate called after throwing an instance of 'rclcpp::exceptions::RCLError'
[robot_state_publisher-3]   what():  failed to create interrupt guard condition: the given context is not valid, either rcl_init() was not called or rcl_shutdown() was called., at /tmp/binarydeb/ros-foxy-rcl-1.1.13/src/rcl/guard_condition.c:67
[ERROR] [robot_state_publisher-3]: process has died [pid 7820, exit code -6, cmd '/opt/ros/foxy/lib/robot_state_publisher/robot_state_publisher --ros-args --params-file /tmp/launch_params_bt2_rfan'].
[spawn_entity.py-5] [INFO] [1659078769.033355970] [spawn_entity]: Spawn Entity started
[spawn_entity.py-5] [INFO] [1659078769.033553329] [spawn_entity]: Loading entity published on topic robot_description
[spawn_entity.py-5] [INFO] [1659078769.034994457] [spawn_entity]: Waiting for entity xml on robot_description
[gzserver-1] [WARN] [1659078769.395969672] [rcl]: Found remap rule 'model_states:=model_states_demo'. This syntax is deprecated. Use '--ros-args --remap model_states:=model_states_demo' instead.
[gzserver-1] [WARN] [1659078769.396061128] [rcl]: Found remap rule 'link_states:=link_states_demo'. This syntax is deprecated. Use '--ros-args --remap link_states:=link_states_demo' instead.
[gzserver-1] [INFO] [1659078769.398552959] [gazebo_ros_state]: Publishing states of gazebo models at [/model_states_demo]
[gzserver-1] [INFO] [1659078769.398782377] [gazebo_ros_state]: Publishing states of gazebo links at [/link_states_demo]
[gzclient   -2] gzclient: /usr/include/boost/smart_ptr/shared_ptr.hpp:734: typename boost::detail::sp_member_access<T>::type boost::shared_ptr<T>::operator->() const [with T = gazebo::rendering::Camera; typename boost::detail::sp_member_access<T>::type = gazebo::rendering::Camera*]: Assertion `px != 0' failed.
[gzclient   -2] Aborted (core dumped)
[ERROR] [gzclient   -2]: process has died [pid 7816, exit code -2, cmd 'gzclient   '].
[ERROR] [spawn_entity.py-5]: process[spawn_entity.py-5] failed to terminate '5' seconds after receiving 'SIGINT', escalating to 'SIGTERM'
[ERROR] [gzserver-1]: process[gzserver-1] failed to terminate '5' seconds after receiving 'SIGINT', escalating to 'SIGTERM'
[INFO] [spawn_entity.py-5]: sending signal 'SIGTERM' to process[spawn_entity.py-5]
[INFO] [gzserver-1]: sending signal 'SIGTERM' to process[gzserver-1]
[ERROR] [gzserver-1]: process has died [pid 7814, exit code -15, cmd 'gzserver /home/aidl/aidl_ws/install/ip010_gazebo/share/ip010_gazebo/worlds/empty_world.world                                                                      -s libgazebo_ros_init.so   -s libgazebo_ros_factory.so   -s libgazebo_ros_force_system.so       '].
[ERROR] [spawn_entity.py-5]: process has died [pid 7824, exit code -15, cmd '/opt/ros/foxy/lib/gazebo_ros/spawn_entity.py -topic robot_description -entity ip010 --ros-args'].

가제보는 켜지는데 로봇이 나오지 않는 현상입니다 .. 그래픽카드 문제일까요? 

(ROS 2 foxy) aidl@aidl-NUC11BTMi7:~/Desktop$ lspci | grep -i VGA
00:02.0 VGA compatible controller: Intel Corporation TigerLake-H GT1 [UHD Graphics] (rev 01)
구글링을 해보니 인텔은 따로 드라이버를 설치하지 않아도 된다고 되어있어서 
auto driver install 만 하였습니다..

**Comment by kimsooyoung** [comment]
```
sudo apt install ros-foxy-rqt-robot-steering
```

위 명령어를 입력하고 다시 실행해보세요.

더불어 NUC에서 gazebo 동작은 보장하지 못합니다. 기억하시겠지만 Gazebo는 노트북에서도 발열이 심했습니다.

**Comment by ghost** [comment]
그럼 그래픽카드 넣으면 괜찮을까요??

**Comment by kimsooyoung** [comment]
음... 도전해보시죠 ㅎㅎ 그런데 노트북도 있는데 NUC에서 하시려는 이유가 뭘까요?

**Comment by ghost** [comment]
실제 로봇에도 응용 해 보고 싶어서요 ㅎㅎ
